import Link from "next/link";
import { Building2, ExternalLink, Mail, MapPin, Phone, ShieldAlert } from "lucide-react";

export default function ContactPage() {
  return <div className="min-h-screen bg-background px-6 py-16 text-foreground"><div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-primary">Contact and support</p><h1 className="mt-4 text-5xl font-black tracking-tight">Start with the right channel.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-foreground/65">This staging portal does not yet have an approved dedicated support desk. Use the official university contact for institutional enquiries and avoid sending passwords, tokens, resumes or verification evidence by ordinary email.</p>
    <div className="mt-12 grid gap-5 md:grid-cols-2"><section className="border border-outline bg-surface p-8"><Building2 className="h-7 w-7 text-primary" /><h2 className="mt-7 text-2xl font-black">Official university contact</h2><div className="mt-6 space-y-4 text-sm leading-relaxed text-foreground/70"><p className="flex gap-3"><MapPin className="mt-0.5 h-5 w-5 flex-none text-primary" /> Netaji Subhas University of Technology, Sector 3, Dwarka, New Delhi - 110078</p><p className="flex gap-3"><Phone className="mt-0.5 h-5 w-5 flex-none text-primary" /> Reception: +91 11 2509 9017, Monday-Friday, 9:30 AM-6:00 PM</p><p className="flex gap-3"><Mail className="mt-0.5 h-5 w-5 flex-none text-primary" /> Academic Section: ar.acad@nsut.ac.in</p></div><a href="https://nsut.ac.in/index.php/en/contact-us" target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-primary">Verify on official NSUT site <ExternalLink className="h-4 w-4" /></a></section>
      <section className="border border-outline p-8"><ShieldAlert className="h-7 w-7 text-primary" /><h2 className="mt-7 text-2xl font-black">What the portal still needs</h2><ul className="mt-6 list-disc space-y-3 pl-5 text-sm leading-relaxed text-foreground/70"><li>A named product owner and support email.</li><li>A privacy/data-protection contact.</li><li>A security incident reporting route.</li><li>Research/IP and moderation appeal owners.</li><li>Published response hours and escalation targets.</li></ul></section></div>
    <section className="mt-8 border border-amber-500/30 bg-amber-500/5 p-7"><h2 className="font-black">Before contacting support</h2><p className="mt-2 text-sm leading-relaxed text-foreground/70">Include the page, approximate time, account role and a non-sensitive description. Never include a password, authentication code, secret key or other person’s private information.</p></section>
    <div className="mt-10 flex flex-wrap gap-5 text-xs font-black uppercase tracking-widest text-primary"><Link href="/privacy">Privacy draft</Link><Link href="/terms">Terms draft</Link><Link href="/ip-policy">IP guidance</Link></div>
  </div></div>;
}
