import PolicyPage from "@/components/legal/PolicyPage";

export default function IpPolicyPage() {
  return <PolicyPage eyebrow="Research and IP guidance" title="Intellectual property, attribution and research outputs" summary="This draft page tells participants what must be clarified before code, datasets, inventions or publications move beyond a student research project." sections={[
    { title: "No automatic ownership transfer", paragraphs: ["Uploading a project, forum post or publication record should not by itself transfer ownership. Ownership depends on applicable law, approved university policy, employment or sponsorship terms and project-specific agreements."] },
    { title: "Background intellectual property", paragraphs: ["Participants should identify code, designs, data, methods and materials created before the project. Background IP remains subject to its existing owner and licence; access for a project does not imply permission for unrelated reuse."] },
    { title: "Project-generated outputs", bullets: ["Record contributors and material technical contributions as work progresses.", "Agree early on stewardship of source code, datasets, prototypes, patentable results and documentation.", "Do not promise ownership shares or licences through a public project listing.", "Escalate sponsored, confidential or potentially patentable work to the authorized research/IP office before disclosure."] },
    { title: "Publication and authorship", paragraphs: ["Authorship should reflect substantial scholarly contribution and disciplinary standards. Contributors who do not meet authorship criteria should be acknowledged. Submission plans, preprints, data release and embargoes should be discussed before publication."] },
    { title: "Open source and open data", bullets: ["Confirm that every dependency and dataset permits the intended use and redistribution.", "Choose an explicit licence; public availability alone is not a licence.", "Remove personal, confidential and restricted information before release.", "Publish provenance, limitations and a citation request with research datasets."] },
    { title: "Inventions and confidentiality", paragraphs: ["Public disclosure can affect patent strategy. Participants should not place confidential sponsor information, unpublished patent details or restricted laboratory data in public posts. The final policy must name the authorized disclosure and technology-transfer process."] },
    { title: "Attribution and takedown", paragraphs: ["The portal needs a documented process for attribution corrections, licence concerns and alleged infringement. A report should identify the work, claimant, basis and requested action without publishing sensitive evidence."] },
    { title: "Relationship to official policy", paragraphs: ["This page is explanatory prototype content only. Any approved NSUT intellectual-property policy, research agreement or sponsor contract takes precedence and should be linked here once verified."] }
  ]} />;
}
