import PolicyPage from "@/components/legal/PolicyPage";

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Privacy notice" title="How NSUT Connect should handle personal data" summary="This draft explains the minimum privacy disclosures and controls the portal needs before an institutional pilot." sections={[
    { title: "Scope and responsibility", paragraphs: ["The final notice must identify the university entity responsible for the portal, the approved privacy contact and the services covered. It should distinguish NSUT Connect from linked external websites."] },
    { title: "Data collected", bullets: ["Account identity, institutional email, role and account status.", "Student academic profile, project applications and application history.", "Faculty profile, verification evidence, projects and publications.", "Forum posts, reports, moderation decisions and audit events.", "Security logs such as time, route, outcome and abuse signals—never passwords or secret keys."] },
    { title: "Why data is used", bullets: ["Authenticate institutional members and enforce role-based access.", "Operate project discovery, applications, faculty review and academic publishing.", "Moderate content, investigate abuse and maintain accountable administrative records.", "Measure reliability and improve the service using aggregated, access-controlled metrics."] },
    { title: "Visibility and sharing", paragraphs: ["The notice must label which profile and authored content fields are public, member-only or restricted to authorized reviewers. Private applications, evidence and audit records must not be exposed through public pages or analytics."], bullets: ["Supabase and Vercel should be named as approved processors only after institutional contracting review.", "External links are separate services with their own privacy terms.", "Personal data should not be sold or used for advertising."] },
    { title: "Retention, correction and deletion", paragraphs: ["Before launch, NSUT must approve retention periods for inactive accounts, unsuccessful applications, verification evidence, moderation records and security logs. The portal needs a documented correction, export, deletion and appeal workflow, including exceptions required for audit or legal obligations."] },
    { title: "Security and incidents", bullets: ["Encryption in transit, least-privilege access, RLS and auditable privileged actions.", "No passwords, tokens, resumes or verification evidence in logs.", "A published incident contact and notification procedure.", "Periodic access, dependency, backup and recovery review."] },
    { title: "Cookies and sessions", paragraphs: ["The portal uses essential authentication cookies or equivalent session storage. Any non-essential analytics requires a separate approval and, where applicable, consent mechanism."] },
    { title: "Questions and complaints", paragraphs: ["The final notice must provide the responsible privacy office, response timeframe and escalation route. Until approved, users should use the official university contact page rather than sending sensitive information through informal channels."] }
  ]} />;
}
